export const DOMAINS = [
  {
    id: 'science',
    name: 'Science',
    emoji: '🔬',
    color: '#2196F3',
    bgColor: '#1a2a4a',
    description: 'Physics, Chemistry, Biology & more',
    topics: ['Physics', 'Chemistry', 'Biology', 'Astronomy', 'Neuroscience'],
  },
  {
    id: 'philosophy',
    name: 'Philosophy',
    emoji: '🧠',
    color: '#9C27B0',
    bgColor: '#2a1a3a',
    description: 'Ethics, Logic, Metaphysics & more',
    topics: ['Ethics', 'Logic', 'Epistemology', 'Metaphysics', 'Stoicism'],
  },
  {
    id: 'history',
    name: 'History',
    emoji: '📜',
    color: '#FF9800',
    bgColor: '#3a2a1a',
    description: 'Ancient, Modern & World History',
    topics: ['Ancient Civilizations', 'World Wars', 'Renaissance', 'Modern Era', 'Cultural History'],
  },
  {
    id: 'technology',
    name: 'Technology',
    emoji: '💻',
    color: '#00BCD4',
    bgColor: '#1a2a2a',
    description: 'CS, AI, Engineering & more',
    topics: ['Computer Science', 'Artificial Intelligence', 'Cybersecurity', 'Engineering', 'Robotics'],
  },
  {
    id: 'mathematics',
    name: 'Mathematics',
    emoji: '∑',
    color: '#FF6B35',
    bgColor: '#2a1a1a',
    description: 'Algebra, Calculus, Geometry & more',
    topics: ['Algebra', 'Calculus', 'Statistics', 'Geometry', 'Number Theory'],
  },
  {
    id: 'arts',
    name: 'Arts & Culture',
    emoji: '🎨',
    color: '#E91E63',
    bgColor: '#2a1a2a',
    description: 'Music, Visual Arts, Literature & more',
    topics: ['Music Theory', 'Visual Arts', 'Literature', 'Film', 'Architecture'],
  },
  {
    id: 'economics',
    name: 'Economics',
    emoji: '📈',
    color: '#4CAF50',
    bgColor: '#1a2a1a',
    description: 'Macro, Micro, Finance & more',
    topics: ['Macroeconomics', 'Microeconomics', 'Personal Finance', 'Markets', 'Behavioral Economics'],
  },
  {
    id: 'psychology',
    name: 'Psychology',
    emoji: '🪬',
    color: '#FFD700',
    bgColor: '#2a2a1a',
    description: 'Cognitive, Social, Behavioral & more',
    topics: ['Cognitive Psychology', 'Social Psychology', 'Behavioral Science', 'Neuroscience', 'Therapy'],
  },
  {
    id: 'linguistics',
    name: 'Linguistics',
    emoji: '🗣️',
    color: '#FF5722',
    bgColor: '#2a1a1a',
    description: 'Languages, Syntax, Semantics & more',
    topics: ['Syntax', 'Semantics', 'Phonetics', 'Language Acquisition', 'Etymology'],
  },
  {
    id: 'geography',
    name: 'Geography',
    emoji: '🌍',
    color: '#009688',
    bgColor: '#1a2a2a',
    description: 'Physical, Human & Political Geography',
    topics: ['Physical Geography', 'Human Geography', 'Geopolitics', 'Cartography', 'Climate'],
  },
]

export const DIFFICULTY_LEVELS = [
  { id: 'beginner', label: 'Beginner', emoji: '🌱', description: 'Just starting out' },
  { id: 'intermediate', label: 'Intermediate', emoji: '🔥', description: 'Know the basics' },
  { id: 'advanced', label: 'Advanced', emoji: '⚡', description: 'Deep knowledge seeker' },
]

export const getDomainById = (id) => DOMAINS.find(d => d.id === id)
